<?php
namespace app\ad\controller;

use think\Controller;
// use app\base\model\User as Us;
// use app\base\model\Record;
// use app\base\model\Member;
// use app\base\model\Conference;
// use app\base\model\Config as Con;
// use app\base\controller\Base as Bas;


class Base extends Controller
{
	/*前台基类默认执行方法*/
	public function _initialize()
	{
		// 获取当前控制器
		$request= \think\Request::instance();
		if( $request->controller() != 'Log')
		{
			//判断是否有登录
			if( session('id') === null )
			{
				// 还没有登录系统，跳转到登录页面
				return $this->redirect( 'log/login' );
			}
		}
		
	}

	/**
	 * 导出Excel表数据	
	 * 	
     *  @param $epl 需要导出的数据
     *  @param $type 导出数据的类型
	 * 	
	 */
	public function excelExport($epl, $type='records')
	{
		header("Content-type:text/html;charset=utf-8");

		// 引入库文件
        \think\Loader::import('Excel.PHPExcel');
        \think\Loader::import('Excel.PHPExcel.IOFactory');

        $letter_arr = 'ABCDEFGHIJKLMNOPKRSTUVWXYZ';

        if($type == 'records')
        {
            $file_name   = "预约记录";
            $sheet_title = '预约记录';
            $cell_value  = ['访客姓名', '员工姓名', '来访人数', '约见开始时间', '约见截止时间', '记录类型', '约见事由', '车牌号码'];
            $cell_key    = ['name', 'ename', 'number', 'start_time', 'end_time', 'visittype', 'reasons', 'car_num'];
        } else if($type == 'visitor'){
            $file_name   = "访客名单";
            $sheet_title = '访客名单';
            $cell_value  = ['访客姓名', '联系方式', '身份证号(选填)'];
            $cell_key    = ['name', 'phone', 'idcard'];
        } else if($type == 'employee'){
            $file_name   = "员工名单";
            $sheet_title = '员工名单';
            $cell_value  = ['员工姓名', '联系方式', '员工地址', '部门(选填)', '身份证号(选填)','员工工号' ];
            $cell_key    = ['name', 'phone', 'address', 'department', 'idcard','code'];
        }
        
		// 拼接文件名
        $file_name .= date("Ymd-His", time()) . ".xls";

        $objExcel = new \PHPExcel();  // 创建一个处理对象实例
        // 创建文件格式写入对象实例, uncomment
        $objWriter = new \PHPExcel_Writer_Excel5($objExcel);   // 用于其他版本格式

        //*************************************
        //设置文档基本属性
        $objProps = $objExcel->getProperties();
        $objProps->setCreator("Zeal Li");
        $objProps->setLastModifiedBy("Zeal Li");
        $objProps->setTitle("Office XLS Test Document");
        $objProps->setSubject("Office XLS Test Document, Demo");
        $objProps->setDescription("Test document, generated by PHPExcel.");
        $objProps->setKeywords("office excel PHPExcel");
        $objProps->setCategory("Test");

        //*************************************
        //设置当前的sheet索引，用于后续的内容操作。
        //一般只有在使用多个sheet的时候才需要显示调用。
        //缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0

        $objExcel->setActiveSheetIndex(0);
        $objActSheet = $objExcel->getActiveSheet();

        //设置当前活动sheet的名称
        $objActSheet->setTitle($sheet_title);


        foreach ($cell_value as $key => $value) {
        	// 设置首单元格内容
            $objActSheet->setCellValue(substr($letter_arr, $key, 1) . '1', $value);
        	// 设置单元格宽度
        	$objActSheet->getColumnDimension(substr($letter_arr, $key, 1))->setWidth(18.5);
        }

        //  遍历访客信息数组，将数据存入对应的excel文件的每个单元格
        for($i = 0; $i < count($epl); $i++)
        {
            if(!isset($epl[$i]['name'])) continue;
            $epl[$i] = $epl[$i]->toArray();

            $j = 0;
            foreach ($cell_value as $key => $value) {
                $objExcel->getActiveSheet()->setCellValueExplicit(substr($letter_arr, $j, 1) . ($i+2), $epl[$i][$cell_key[$key]]);
            	$j++;
            }
        }

        //设置字体
        $objStyleA = $objActSheet->getStyle('A');
        $objStyleA = $objStyleA->getFont();
        $objStyleA->setName('宋体');
        $objStyleA->setSize(10);
        $objStyleA->setBold(true);
        $objStyleA->getColor()->setARGB('FF999999');

        //*************************************
        //输出内容
        //

        $output_file_name = $file_name;
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header('Content-Disposition:attachment;filename="' . $output_file_name . '"');//兼容其他浏览器到文件
        header('Content-Disposition:filename="' . $output_file_name . '"');  //兼容IE浏览器到文件
        header('Content-Disposition:inline;filename="'.$output_file_name.'"');  //到浏览器
        header("Content-Transfer-Encoding: binary");
        header("Expires: 0");
        header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Pragma: no-cache");
        $objWriter->save('./excel/'.$output_file_name);
        return $output_file_name;
	}

      #curl http请求 整合get和post
    static public function getContents($url, $data='')
    {
        $header = array(
            'Content-Type:application/json;charset=utf-8',
            // 'Content-Length: ' .strlen($data)
        );
        $curl = curl_init();
        curl_setopt($curl,CURLOPT_URL,$url);
        curl_setopt($curl,CURLOPT_HTTPHEADER,$header);
        curl_setopt($curl,CURLOPT_SSL_VERIFYPEER,FALSE);
        curl_setopt($curl,CURLOPT_SSL_VERIFYHOST,FALSE);
        if(!empty($data))
        {
            curl_setopt($curl,1,1);
            curl_setopt($curl,CURLOPT_POSTFIELDS,$data);
            // curl_setopt($curl,1,$data);
        }
        // echo "444";
        // print_r($data);
        // die;
        curl_setopt($curl,CURLOPT_RETURNTRANSFER,1);
        $output = curl_exec($curl);
        curl_close($curl);
        return $output;
    }

}
